AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.3
  DisplayCopNames: true
  Exclude:
    - "test/dummy/**/*"

### Style ###

Style/AccessModifierIndentation:
  Enabled: true

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Style/AndOr:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Style/CaseIndentation:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true

Style/DotPosition:
  Enabled: true

Style/EachWithObject:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/GlobalVars:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Style/IndentAssignment:
  Enabled: true

Style/IndentationConsistency:
  # The difference between `rails` and `normal` is that the `rails` style
  # prescribes that in classes and modules the `protected` and `private`
  # modifier keywords shall be indented the same as public methods and that
  # protected and private members shall be indented one step more than the
  # modifiers. Other than that, both styles mean that entities on the same
  # logical depth shall have the same indentation.
  Enabled: true
  EnforcedStyle: normal

Style/IndentationWidth:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Style/MethodName:
  Enabled: true

Style/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line

Style/NestedTernaryOperator:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': ()
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': ()
    '%W': ()
    '%x': ()

Style/RegexpLiteral:
  Enabled: true
  EnforcedStyle: mixed

Style/SpaceAroundOperators:
  Enabled: true

Style/SpaceBeforeBlockBraces:
  Enabled: true

Style/SpaceInsideBlockBraces:
  Enabled: true

Style/SpaceInsideHashLiteralBraces:
  Enabled: true

Style/StabbyLambdaParentheses:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/SymbolProc:
  Enabled: true

Style/Tab:
  Enabled: true

Style/TrailingWhitespace:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true

Style/VariableName:
  Enabled: true

Style/WordArray:
  EnforcedStyle: percent

### Lint ###

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Lint/EndAlignment:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true
  AllowUnusedKeywordArguments: true

Lint/UnreachableCode:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/Void:
  Enabled: true
