AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.7
  DisplayCopNames: true
  Exclude:
    - "test/dummy/**/*"

### Style ###

Layout/AccessModifierIndentation:
  Enabled: true

Style/Alias:
  Enabled: true
  EnforcedStyle: prefer_alias_method

Style/AndOr:
  Enabled: true

Style/BlockDelimiters:
  Enabled: true

Layout/CaseIndentation:
  Enabled: true

Style/CollectionMethods:
  Enabled: true

Style/ConditionalAssignment:
  Enabled: true

Layout/DotPosition:
  Enabled: true

Style/EachWithObject:
  Enabled: true

Style/EmptyElse:
  Enabled: true

Style/GlobalVars:
  Enabled: true

Style/HashSyntax:
  Enabled: true

Layout/IndentationConsistency:
  # The difference between `rails` and `normal` is that the `rails` style
  # prescribes that in classes and modules the `protected` and `private`
  # modifier keywords shall be indented the same as public methods and that
  # protected and private members shall be indented one step more than the
  # modifiers. Other than that, both styles mean that entities on the same
  # logical depth shall have the same indentation.
  Enabled: true
  EnforcedStyle: normal

Layout/IndentationWidth:
  Enabled: true

Style/MethodDefParentheses:
  Enabled: true

Naming/MethodName:
  Enabled: true

Layout/MultilineAssignmentLayout:
  Enabled: true
  EnforcedStyle: same_line

Style/NestedTernaryOperator:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': ()
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': ()
    '%W': ()
    '%x': ()

Style/RegexpLiteral:
  Enabled: true
  EnforcedStyle: mixed

Layout/SpaceAroundOperators:
  Enabled: true

Layout/SpaceBeforeBlockBraces:
  Enabled: true

Layout/SpaceInsideBlockBraces:
  Enabled: true

Layout/SpaceInsideHashLiteralBraces:
  Enabled: true

Style/StabbyLambdaParentheses:
  Enabled: true

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/SymbolProc:
  Enabled: true

Layout/Tab:
  Enabled: true

Layout/TrailingWhitespace:
  Enabled: true

Style/TrivialAccessors:
  Enabled: true

Naming/VariableName:
  Enabled: true

Style/WordArray:
  EnforcedStyle: percent

### Lint ###

Lint/DeprecatedClassMethods:
  Enabled: true

Lint/DuplicateMethods:
  Enabled: true

Layout/EndAlignment:
  Enabled: true

Lint/UnusedBlockArgument:
  Enabled: true

Lint/UnusedMethodArgument:
  Enabled: true
  AllowUnusedKeywordArguments: true

Lint/UnreachableCode:
  Enabled: true

Lint/ShadowingOuterLocalVariable:
  Enabled: true

Lint/Void:
  Enabled: true
